version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Berlin"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      tailwind:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      next:
        patterns:
          - "next"
          - "eslint-config-next"
    ignore:
      - dependency-name: "typescript"
        versions:
          - ">= 7.0.0, < 8.0.0"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Berlin"
